version: '3'
services:
  node-app:
    container_name: express-node-app-con
    build:
      context: .
      args:
        - NODE_ENV=
    environment:
      - NODE_ENV=PRODUCTION
    command: npm start
